import { Cancha, Equipo, Fecha } from './torneo';

export const fechas: Fecha[] = [
  {
    id: '1',
    jugada: true,
    canchaId: '8',
    equipoOrganizadorId: '9',
    fecha: '19/03/2022',
    partidos: [
      {
        id: '1',
        jugado: true,
        horario: '15:00',
        equipoLocalId: '4',
        equipoVisitanteId: '10',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '2',
        horario: '16:10',
        equipoLocalId: '6',
        equipoVisitanteId: '7',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '3',
        horario: '17:20',
        equipoLocalId: '1',
        equipoVisitanteId: '11',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '4',
        horario: '18:30',
        equipoLocalId: '9',
        equipoVisitanteId: '5',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '5',
        horario: '19:40',
        equipoLocalId: '3',
        equipoVisitanteId: '12',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '6',
        horario: '20:50',
        equipoLocalId: '2',
        equipoVisitanteId: '8',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
    ],
  },
  {
    id: '2',
    jugada: true,
    canchaId: '2',
    equipoOrganizadorId: '2',
    fecha: '26/03/2022',
    partidos: [
      {
        jugado: true,
        id: '7',
        horario: '15:00',
        equipoLocalId: '7',
        equipoVisitanteId: '11',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '8',
        horario: '16:10',
        equipoLocalId: '4',
        equipoVisitanteId: '5',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '9',
        horario: '17:20',
        equipoLocalId: '1',
        equipoVisitanteId: '9',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '10',
        horario: '18:30',
        equipoLocalId: '7',
        equipoVisitanteId: '12',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '11',
        horario: '19:40',
        equipoLocalId: '6',
        equipoVisitanteId: '3',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '12',
        horario: '20:50',
        equipoLocalId: '2',
        equipoVisitanteId: '10',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
    ],
  },
  {
    id: '3',
    jugada: true,
    canchaId: '10',
    equipoOrganizadorId: '6',
    fecha: '02/04/2022',
    partidos: [
      {
        jugado: true,
        id: '13',
        horario: '15:00',
        equipoLocalId: '6',
        equipoVisitanteId: '2',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '14',
        horario: '16:10',
        equipoLocalId: '5',
        equipoVisitanteId: '1',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '15',
        horario: '17:20',
        equipoLocalId: '7',
        equipoVisitanteId: '10',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '16',
        horario: '18:30',
        equipoLocalId: '11',
        equipoVisitanteId: '4',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '17',
        horario: '19:40',
        equipoLocalId: '3',
        equipoVisitanteId: '8',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: true,
        id: '18',
        horario: '20:50',
        equipoLocalId: '12',
        equipoVisitanteId: '9',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
    ],
  },
  {
    id: '4',
    jugada: false,
    canchaId: '1',
    equipoOrganizadorId: '1',
    fecha: '09/04/2022',
    partidos: [
      {
        jugado: false,
        id: '19',
        horario: '15:00',
        equipoLocalId: '2',
        equipoVisitanteId: '11',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: false,
        id: '20',
        horario: '16:10',
        equipoLocalId: '9',
        equipoVisitanteId: '4',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: false,
        id: '21',
        horario: '17:20',
        equipoLocalId: '3',
        equipoVisitanteId: '10',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: false,
        id: '22',
        horario: '18:30',
        equipoLocalId: '5',
        equipoVisitanteId: '7',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: false,
        id: '23',
        horario: '19:40',
        equipoLocalId: '8',
        equipoVisitanteId: '6',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
      {
        jugado: false,
        id: '24',
        horario: '20:50',
        equipoLocalId: '1',
        equipoVisitanteId: '12',
        amarillasLocalId: [],
        amarillasVisitanteId: [],
        golesLocalId: [],
        golesVisitanteId: [],
        rojasLocalId: [],
        rojasVisitanteId: [],
      },
    ],
  },
  {
    id: '5',
    jugada: false,
    canchaId: '11',
    equipoOrganizadorId: '12',
    fecha: '16/04/2022',
    partidos: [],
  },
  {
    id: '6',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '5',
    fecha: '23/04/2022',
    partidos: [],
  },
  {
    id: '7',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '4',
    fecha: '30/04/2022',
    partidos: [],
  },
  {
    id: '8',
    jugada: false,
    canchaId: '6',
    equipoOrganizadorId: '7',
    fecha: '07/05/2022',
    partidos: [],
  },
  {
    id: '9',
    jugada: false,
    canchaId: '7',
    equipoOrganizadorId: '8',
    fecha: '14/05/2022',
    partidos: [],
  },
  {
    id: '10',
    jugada: false,
    canchaId: '3',
    equipoOrganizadorId: '3',
    fecha: '21/05/2022',
    partidos: [],
  },
  {
    id: '11',
    jugada: false,
    canchaId: '9',
    equipoOrganizadorId: '10',
    fecha: '28/05/2022',
    partidos: [],
  },
  {
    id: '12',
    jugada: false,
    canchaId: '10',
    equipoOrganizadorId: '11',
    fecha: '04/06/2022',
    partidos: [],
  },
];

export const equipos: Equipo[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    imagen: './assets/escudos/baru.png',
    jugadores: [],
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    imagen: './assets/escudos/cagu.png',
    jugadores: [],
  },
  {
    id: '3',
    nombre: 'Azul Azul',
    imagen: './assets/escudos/azul-azul.png',
    jugadores: [],
  },
  {
    id: '4',
    nombre: 'C.A. Baylina A',
    imagen: './assets/escudos/baylina.png',
    jugadores: [],
  },
  {
    id: '5',
    nombre: 'C.A. Baylina B',
    imagen: './assets/escudos/baylina.png',
    jugadores: [],
  },
  {
    id: '6',
    nombre: 'D. Berduc',
    imagen: './assets/escudos/berduc.png',
    jugadores: [],
  },
  {
    id: '7',
    nombre: 'C.D. Hambis',
    imagen: './assets/escudos/hambis.png',
    jugadores: [],
  },
  {
    id: '8',
    nombre: 'C.S D. Huracán',
    imagen: './assets/escudos/hocker.png',
    jugadores: [],
  },
  {
    id: '9',
    nombre: 'C. Independiente',
    imagen: './assets/escudos/jubileo.png',
    jugadores: [],
  },
  {
    id: '10',
    nombre: 'C.A. Las Palmas',
    imagen: './assets/escudos/las-palmas.png',
    jugadores: [],
  },
  {
    id: '11',
    nombre: 'C.D. San Antonio',
    imagen: './assets/escudos/san-antonio.png',
    jugadores: [],
  },
  {
    id: '12',
    nombre: 'S. Villa Clara',
    imagen: './assets/escudos/villa-clara.png',
    jugadores: [],
  },
];

export const canchas: Cancha[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    localidad: 'Arroyo Barú',
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    localidad: 'La Clarita',
  },
  {
    id: '3',
    localidad: 'General Campos',
    nombre: 'Azul Azul',
  },
  {
    id: '4',
    nombre: 'C.A. Baylina',
    localidad: 'Baylina',
  },

  {
    id: '5',
    nombre: 'D. Berduc',
    localidad: 'Berduc',
  },
  {
    id: '6',
    nombre: 'C.D. Hambis',
    localidad: 'Colonia Hambis',
  },
  {
    id: '7',
    nombre: 'C.S D. Huracán',
    localidad: 'Colonia Hocker',
  },
  {
    id: '8',
    nombre: 'C. Independiente',
    localidad: 'Jubileo',
  },
  {
    id: '9',
    nombre: 'C.A. Las Palmas',
    localidad: 'Colonia San Hernesto',
  },
  {
    id: '10',
    nombre: 'C.D. San Antonio',
    localidad: 'Pueblo Cazes',
  },
  {
    id: '11',
    nombre: 'S. Villa Clara',
    localidad: 'Villa Clara',
  },
];
