import { Cancha, Equipo, Fecha, Jugador, Partido } from './torneo';

export const fechas: Fecha[] = [
  {
    id: '1',
    jugada: true,
    canchaId: '8',
    equipoOrganizadorId: '9',
    fecha: '19/03/2022',
    partidos: ['1', '2', '3', '4', '5', '6'],
  },
  {
    id: '2',
    jugada: true,
    canchaId: '2',
    equipoOrganizadorId: '2',
    fecha: '26/03/2022',
    partidos: ['7', '8', '9', '10', '11', '12'],
  },
  {
    id: '3',
    jugada: true,
    canchaId: '10',
    equipoOrganizadorId: '6',
    fecha: '02/04/2022',
    partidos: ['13', '14', '15', '16', '17', '18'],
  },
  {
    id: '4',
    jugada: false,
    canchaId: '1',
    equipoOrganizadorId: '1',
    fecha: '09/04/2022',
    partidos: ['19', '20', '21', '22', '23', '24'],
  },
  {
    id: '5',
    jugada: false,
    canchaId: '11',
    equipoOrganizadorId: '12',
    fecha: '16/04/2022',
    partidos: [],
  },
  {
    id: '6',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '5',
    fecha: '23/04/2022',
    partidos: [],
  },
  {
    id: '7',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '4',
    fecha: '30/04/2022',
    partidos: [],
  },
  {
    id: '8',
    jugada: false,
    canchaId: '6',
    equipoOrganizadorId: '7',
    fecha: '07/05/2022',
    partidos: [],
  },
  {
    id: '9',
    jugada: false,
    canchaId: '7',
    equipoOrganizadorId: '8',
    fecha: '14/05/2022',
    partidos: [],
  },
  {
    id: '10',
    jugada: false,
    canchaId: '3',
    equipoOrganizadorId: '3',
    fecha: '21/05/2022',
    partidos: [],
  },
  {
    id: '11',
    jugada: false,
    canchaId: '9',
    equipoOrganizadorId: '10',
    fecha: '28/05/2022',
    partidos: [],
  },
  {
    id: '12',
    jugada: false,
    canchaId: '10',
    equipoOrganizadorId: '11',
    fecha: '04/06/2022',
    partidos: [],
  },
];

export const equipos: Equipo[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    imagen: './assets/escudos/baru.png',
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    imagen: './assets/escudos/cagu.png',
  },
  {
    id: '3',
    nombre: 'Azul Azul',
    imagen: './assets/escudos/azul-azul.png',
  },
  {
    id: '4',
    nombre: 'C.A. Baylina A',
    imagen: './assets/escudos/baylina.png',
  },
  {
    id: '5',
    nombre: 'C.A. Baylina B',
    imagen: './assets/escudos/baylina.png',
  },
  {
    id: '6',
    nombre: 'D. Berduc',
    imagen: './assets/escudos/berduc.png',
  },
  {
    id: '7',
    nombre: 'C.D. Hambis',
    imagen: './assets/escudos/hambis.png',
  },
  {
    id: '8',
    nombre: 'C.S D. Huracán',
    imagen: './assets/escudos/hocker.png',
  },
  {
    id: '9',
    nombre: 'C. Independiente',
    imagen: './assets/escudos/jubileo.png',
  },
  {
    id: '10',
    nombre: 'C.A. Las Palmas',
    imagen: './assets/escudos/las-palmas.png',
  },
  {
    id: '11',
    nombre: 'C.D. San Antonio',
    imagen: './assets/escudos/san-antonio.png',
  },
  {
    id: '12',
    nombre: 'S. Villa Clara',
    imagen: './assets/escudos/villa-clara.png',
  },
];

export const canchas: Cancha[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    localidad: 'Arroyo Barú',
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    localidad: 'La Clarita',
  },
  {
    id: '3',
    localidad: 'General Campos',
    nombre: 'Azul Azul',
  },
  {
    id: '4',
    nombre: 'C.A. Baylina',
    localidad: 'Baylina',
  },

  {
    id: '5',
    nombre: 'D. Berduc',
    localidad: 'Berduc',
  },
  {
    id: '6',
    nombre: 'C.D. Hambis',
    localidad: 'Colonia Hambis',
  },
  {
    id: '7',
    nombre: 'C.S D. Huracán',
    localidad: 'Colonia Hocker',
  },
  {
    id: '8',
    nombre: 'C. Independiente',
    localidad: 'Jubileo',
  },
  {
    id: '9',
    nombre: 'C.A. Las Palmas',
    localidad: 'Colonia San Hernesto',
  },
  {
    id: '10',
    nombre: 'C.D. San Antonio',
    localidad: 'Pueblo Cazes',
  },
  {
    id: '11',
    nombre: 'S. Villa Clara',
    localidad: 'Villa Clara',
  },
];

export const partidos: Partido[] = [
  {
    jugado: true,
    id: '13',
    horario: '15:00',
    equipoLocalId: '6',
    equipoVisitanteId: '2',
    amarillasLocalId: ['5', '6', '7'],
    amarillasVisitanteId: [],
    golesLocalId: ['4'],
    golesVisitanteId: ['8'],
    rojasLocalId: [],
    rojasVisitanteId: ['9'],
  },
  {
    jugado: true,
    id: '14',
    horario: '16:10',
    equipoLocalId: '5',
    equipoVisitanteId: '1',
    amarillasLocalId: ['10', '11'],
    amarillasVisitanteId: ['13', '14', '3'],
    golesLocalId: [],
    golesVisitanteId: ['12'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '15',
    horario: '17:20',
    equipoLocalId: '7',
    equipoVisitanteId: '10',
    amarillasLocalId: ['16', '17', '18'],
    amarillasVisitanteId: ['19', '21'],
    golesLocalId: ['15'],
    golesVisitanteId: ['19', '20'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '16',
    horario: '18:30',
    equipoLocalId: '11',
    equipoVisitanteId: '4',
    amarillasLocalId: ['22', '25'],
    amarillasVisitanteId: ['26', '27'],
    golesLocalId: ['22', '23', '24'],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: ['28'],
  },
  {
    jugado: true,
    id: '17',
    horario: '19:40',
    equipoLocalId: '3',
    equipoVisitanteId: '8',
    amarillasLocalId: ['29'],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: ['30'],
  },
  {
    jugado: true,
    id: '18',
    horario: '20:50',
    equipoLocalId: '12',
    equipoVisitanteId: '9',
    amarillasLocalId: ['32', '33'],
    amarillasVisitanteId: ['35', '36'],
    golesLocalId: ['31'],
    golesVisitanteId: [],
    rojasLocalId: ['34'],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '19',
    horario: '15:00',
    equipoLocalId: '2',
    equipoVisitanteId: '11',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '20',
    horario: '16:10',
    equipoLocalId: '9',
    equipoVisitanteId: '4',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '21',
    horario: '17:20',
    equipoLocalId: '3',
    equipoVisitanteId: '10',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '22',
    horario: '18:30',
    equipoLocalId: '5',
    equipoVisitanteId: '7',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '23',
    horario: '19:40',
    equipoLocalId: '8',
    equipoVisitanteId: '6',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: false,
    id: '24',
    horario: '20:50',
    equipoLocalId: '1',
    equipoVisitanteId: '12',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    id: '1',
    jugado: true,
    horario: '15:00',
    equipoLocalId: '4',
    equipoVisitanteId: '10',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '2',
    horario: '16:10',
    equipoLocalId: '6',
    equipoVisitanteId: '7',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '3',
    horario: '17:20',
    equipoLocalId: '1',
    equipoVisitanteId: '11',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '4',
    horario: '18:30',
    equipoLocalId: '9',
    equipoVisitanteId: '5',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '5',
    horario: '19:40',
    equipoLocalId: '3',
    equipoVisitanteId: '12',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '6',
    horario: '20:50',
    equipoLocalId: '2',
    equipoVisitanteId: '8',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '7',
    horario: '15:00',
    equipoLocalId: '7',
    equipoVisitanteId: '11',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '8',
    horario: '16:10',
    equipoLocalId: '4',
    equipoVisitanteId: '5',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '9',
    horario: '17:20',
    equipoLocalId: '1',
    equipoVisitanteId: '9',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: ['2', '2', '2', '14'],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '10',
    horario: '18:30',
    equipoLocalId: '7',
    equipoVisitanteId: '12',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '11',
    horario: '19:40',
    equipoLocalId: '6',
    equipoVisitanteId: '3',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '12',
    horario: '20:50',
    equipoLocalId: '2',
    equipoVisitanteId: '10',
    amarillasLocalId: [],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
];

export const jugadores: Jugador[] = [
  {
    id: '1',
    equipoId: '1',
    nombre: 'Lucas Rossier',
    fechaNacimiento: '09/04/1998',
    posicion: 'Mediocampista',
  },
  {
    id: '2',
    equipoId: '1',
    nombre: 'Lihuen Segovia Grabois',
    posicion: 'Delantero',
  },
  {
    id: '3',
    equipoId: '1',
    nombre: 'Jair Rossier',
    posicion: 'Defensor',
  },
  {
    id: '4',
    equipoId: '6',
    nombre: 'Milton Amarillo',
  },
  {
    id: '5',
    equipoId: '6',
    nombre: 'Marcos Vincon',
  },
  {
    id: '6',
    equipoId: '6',
    nombre: 'Emiliano Casse',
  },
  {
    id: '7',
    equipoId: '6',
    nombre: 'Joaquin Zermathen',
  },
  {
    id: '8',
    equipoId: '2',
    nombre: 'Santiago Valdez',
  },
  {
    id: '9',
    equipoId: '2',
    nombre: 'Eduardo Maciel',
  },
  {
    id: '10',
    equipoId: '5',
    nombre: 'Mauto Orcellet',
  },
  {
    id: '11',
    equipoId: '5',
    nombre: 'Walter Veron',
  },
  {
    id: '12',
    equipoId: '1',
    nombre: 'Benjamín Mengeon',
  },
  {
    id: '13',
    equipoId: '1',
    nombre: 'Alejandro Barreto',
  },
  {
    id: '14',
    equipoId: '1',
    nombre: 'Gabriel Fleitas',
  },
  {
    id: '15',
    equipoId: '7',
    nombre: 'Brian Castro',
  },
  {
    id: '16',
    equipoId: '7',
    nombre: 'Sebastián Orcellet',
  },
  {
    id: '17',
    equipoId: '7',
    nombre: 'Brian Riquelme',
  },
  {
    id: '18',
    equipoId: '7',
    nombre: 'Daian Godoy',
  },
  {
    id: '19',
    equipoId: '10',
    nombre: 'Facundo Lederhos',
  },
  {
    id: '20',
    equipoId: '10',
    nombre: 'Guido Retamar',
  },
  {
    id: '21',
    equipoId: '10',
    nombre: 'Pablo Gómez',
  },
  {
    id: '22',
    equipoId: '11',
    nombre: 'Fabio Berdala',
  },
  {
    id: '23',
    equipoId: '11',
    nombre: 'Javier Combet',
  },
  {
    id: '24',
    equipoId: '11',
    nombre: 'Juan Gómez',
  },
  {
    id: '25',
    equipoId: '11',
    nombre: 'Emiliano Rodríguez',
  },
  {
    id: '26',
    equipoId: '4',
    nombre: 'Giovanni Fontana',
  },
  {
    id: '27',
    equipoId: '4',
    nombre: 'Eduardo Chareun',
  },
  {
    id: '28',
    equipoId: '4',
    nombre: 'Roger Cruz',
  },
  {
    id: '29',
    equipoId: '3',
    nombre: 'Santiago Rebord',
  },
  {
    id: '30',
    equipoId: '8',
    nombre: 'Fabricio Rougier',
  },
  {
    id: '31',
    equipoId: '12',
    nombre: 'Joel Martínez',
  },
  {
    id: '32',
    equipoId: '12',
    nombre: 'Esteban Valloris',
  },
  {
    id: '33',
    equipoId: '12',
    nombre: 'Guido Benegas',
  },
  {
    id: '34',
    equipoId: '12',
    nombre: 'Ángel Martínez',
  },
  {
    id: '35',
    equipoId: '9',
    nombre: 'Agustín Galves',
  },
  {
    id: '36',
    equipoId: '9',
    nombre: 'Dardo Rivero',
  },
];
