import { Cancha, Equipo, Fecha, Jugador, Partido } from './torneo';

export const fechas: Fecha[] = [
  {
    id: '1',
    jugada: true,
    canchaId: '8',
    equipoOrganizadorId: '9',
    fecha: '19/03/2022',
    partidos: ['1', '2', '3', '4', '5', '6'],
  },
  {
    id: '2',
    jugada: true,
    canchaId: '2',
    equipoOrganizadorId: '2',
    fecha: '26/03/2022',
    partidos: ['7', '8', '9', '10', '11', '12'],
  },
  {
    id: '3',
    jugada: true,
    canchaId: '10',
    equipoOrganizadorId: '6',
    fecha: '02/04/2022',
    partidos: ['13', '14', '15', '16', '17', '18'],
  },
  {
    id: '4',
    jugada: true,
    canchaId: '1',
    equipoOrganizadorId: '1',
    fecha: '09/04/2022',
    partidos: ['19', '20', '21', '22', '23', '24'],
  },
  {
    id: '5',
    jugada: false,
    canchaId: '11',
    equipoOrganizadorId: '12',
    fecha: '16/04/2022',
    partidos: ['25', '26', '27', '28', '29', '30'],
  },
  {
    id: '6',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '5',
    fecha: '23/04/2022',
    partidos: ['31', '32', '33', '34', '35', '36'],
  },
  {
    id: '7',
    jugada: false,
    canchaId: '4',
    equipoOrganizadorId: '4',
    fecha: '30/04/2022',
    partidos: ['37', '38', '39', '40', '41', '42'],
  },
  {
    id: '8',
    jugada: false,
    canchaId: '6',
    equipoOrganizadorId: '7',
    fecha: '07/05/2022',
    partidos: ['43', '44', '45', '46', '47', '48'],
  },
  {
    id: '9',
    jugada: false,
    canchaId: '7',
    equipoOrganizadorId: '8',
    fecha: '14/05/2022',
    partidos: ['49', '50', '51', '52', '53', '54'],
  },
  {
    id: '10',
    jugada: false,
    canchaId: '3',
    equipoOrganizadorId: '3',
    fecha: '21/05/2022',
    partidos: ['55', '56', '57', '58', '59', '60'],
  },
  {
    id: '11',
    jugada: false,
    canchaId: '9',
    equipoOrganizadorId: '10',
    fecha: '28/05/2022',
    partidos: ['61', '62', '63', '64', '65', '66'],
  },
  {
    id: '12',
    jugada: false,
    canchaId: '10',
    equipoOrganizadorId: '11',
    fecha: '04/06/2022',
    partidos: ['67', '68', '69', '70', '71', '72'],
  },
];

export const equipos: Equipo[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    imagen: './assets/escudos/baru.png',
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    imagen: './assets/escudos/cagu.png',
  },
  {
    id: '3',
    nombre: 'Azul Azul',
    imagen: './assets/escudos/azul-azul.png',
  },
  {
    id: '4',
    nombre: 'C.A. Baylina A',
    imagen: './assets/escudos/baylina.png',
  },
  {
    id: '5',
    nombre: 'C.A. Baylina B',
    imagen: './assets/escudos/baylina.png',
  },
  {
    id: '6',
    nombre: 'D. Berduc',
    imagen: './assets/escudos/berduc.png',
  },
  {
    id: '7',
    nombre: 'C.D. Hambis',
    imagen: './assets/escudos/hambis.png',
  },
  {
    id: '8',
    nombre: 'C.S D. Huracán',
    imagen: './assets/escudos/hocker.png',
  },
  {
    id: '9',
    nombre: 'C. Independiente',
    imagen: './assets/escudos/jubileo.png',
  },
  {
    id: '10',
    nombre: 'C.A. Las Palmas',
    imagen: './assets/escudos/las-palmas.png',
  },
  {
    id: '11',
    nombre: 'C.D. San Antonio',
    imagen: './assets/escudos/san-antonio.png',
  },
  {
    id: '12',
    nombre: 'S. Villa Clara',
    imagen: './assets/escudos/villa-clara.png',
  },
];

export const canchas: Cancha[] = [
  {
    id: '1',
    nombre: 'C.D. Barú',
    localidad: 'Arroyo Barú',
  },
  {
    id: '2',
    nombre: 'C.A. Gral. Urquiza',
    localidad: 'La Clarita',
  },
  {
    id: '3',
    localidad: 'General Campos',
    nombre: 'Azul Azul',
  },
  {
    id: '4',
    nombre: 'C.A. Baylina',
    localidad: 'Baylina',
  },

  {
    id: '5',
    nombre: 'D. Berduc',
    localidad: 'Berduc',
  },
  {
    id: '6',
    nombre: 'C.D. Hambis',
    localidad: 'Colonia Hambis',
  },
  {
    id: '7',
    nombre: 'C.S D. Huracán',
    localidad: 'Colonia Hocker',
  },
  {
    id: '8',
    nombre: 'C. Independiente',
    localidad: 'Jubileo',
  },
  {
    id: '9',
    nombre: 'C.A. Las Palmas',
    localidad: 'Colonia San Hernesto',
  },
  {
    id: '10',
    nombre: 'C.D. San Antonio',
    localidad: 'Pueblo Cazes',
  },
  {
    id: '11',
    nombre: 'S. Villa Clara',
    localidad: 'Villa Clara',
  },
];

export const partidos: Partido[] = [
  {
    id: '1',
    jugado: true,
    horario: '15:00',
    equipoLocalId: '4',
    equipoVisitanteId: '10',
    amarillasLocalId: ['26', '38', '37'],
    amarillasVisitanteId: ['40', '41'],
    golesLocalId: [],
    golesVisitanteId: ['19'],
    rojasLocalId: [],
    rojasVisitanteId: ['39'],
  },
  {
    jugado: true,
    id: '2',
    horario: '16:10',
    equipoLocalId: '6',
    equipoVisitanteId: '7',
    amarillasLocalId: ['42'],
    amarillasVisitanteId: ['43', '44', '45'],
    golesLocalId: [],
    golesVisitanteId: ['43'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '3',
    horario: '17:20',
    equipoLocalId: '1',
    equipoVisitanteId: '11',
    amarillasLocalId: ['46'],
    amarillasVisitanteId: ['24', '48', '49'],
    golesLocalId: ['1'],
    golesVisitanteId: ['47'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '4',
    horario: '18:30',
    equipoLocalId: '9',
    equipoVisitanteId: '5',
    amarillasLocalId: ['36', '50'],
    amarillasVisitanteId: ['52', '53'],
    golesLocalId: [],
    golesVisitanteId: ['51'],
    rojasLocalId: [],
    rojasVisitanteId: ['51'],
  },
  {
    jugado: true,
    id: '5',
    horario: '19:40',
    equipoLocalId: '3',
    equipoVisitanteId: '12',
    amarillasLocalId: [],
    amarillasVisitanteId: ['31'],
    golesLocalId: ['54'],
    golesVisitanteId: ['31'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '6',
    horario: '20:50',
    equipoLocalId: '2',
    equipoVisitanteId: '8',
    amarillasLocalId: ['9', '55', '56', '57'],
    amarillasVisitanteId: ['30', '59', '58'],
    golesLocalId: [],
    golesVisitanteId: ['58'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '7',
    horario: '15:00',
    equipoLocalId: '7',
    equipoVisitanteId: '11',
    amarillasLocalId: ['45'],
    amarillasVisitanteId: ['61', '62'],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: ['60'],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '8',
    horario: '16:10',
    equipoLocalId: '4',
    equipoVisitanteId: '5',
    amarillasLocalId: ['28', '37', '64'],
    amarillasVisitanteId: ['53', '10'],
    golesLocalId: ['63'],
    golesVisitanteId: ['53'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '9',
    horario: '17:20',
    equipoLocalId: '1',
    equipoVisitanteId: '9',
    amarillasLocalId: ['65'],
    amarillasVisitanteId: ['35', '66', '50', '67', '68'],
    golesLocalId: ['2', '2', '2', '14'],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '10',
    horario: '18:30',
    equipoLocalId: '8',
    equipoVisitanteId: '12',
    amarillasLocalId: ['69', '70', '71', '72', '73'],
    amarillasVisitanteId: ['74'],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '11',
    horario: '19:40',
    equipoLocalId: '6',
    equipoVisitanteId: '3',
    amarillasLocalId: ['5'],
    amarillasVisitanteId: ['76'],
    golesLocalId: [],
    golesVisitanteId: ['75'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '12',
    horario: '20:50',
    equipoLocalId: '2',
    equipoVisitanteId: '10',
    amarillasLocalId: ['9', '55'],
    amarillasVisitanteId: ['77', '78', '79', '80'],
    golesLocalId: ['9'],
    golesVisitanteId: ['19'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '13',
    horario: '15:00',
    equipoLocalId: '6',
    equipoVisitanteId: '2',
    amarillasLocalId: ['5', '6', '7'],
    amarillasVisitanteId: [],
    golesLocalId: ['4'],
    golesVisitanteId: ['8'],
    rojasLocalId: [],
    rojasVisitanteId: ['9'],
  },
  {
    jugado: true,
    id: '14',
    horario: '16:10',
    equipoLocalId: '5',
    equipoVisitanteId: '1',
    amarillasLocalId: ['10', '11'],
    amarillasVisitanteId: ['13', '14', '3'],
    golesLocalId: [],
    golesVisitanteId: ['12'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '15',
    horario: '17:20',
    equipoLocalId: '7',
    equipoVisitanteId: '10',
    amarillasLocalId: ['16', '17', '18'],
    amarillasVisitanteId: ['19', '21'],
    golesLocalId: ['15'],
    golesVisitanteId: ['19', '20'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '16',
    horario: '18:30',
    equipoLocalId: '11',
    equipoVisitanteId: '4',
    amarillasLocalId: ['22', '25'],
    amarillasVisitanteId: ['26', '27'],
    golesLocalId: ['22', '23', '24'],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: ['28'],
  },
  {
    jugado: true,
    id: '17',
    horario: '19:40',
    equipoLocalId: '3',
    equipoVisitanteId: '8',
    amarillasLocalId: ['29'],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: ['30'],
  },
  {
    jugado: true,
    id: '18',
    horario: '20:50',
    equipoLocalId: '12',
    equipoVisitanteId: '9',
    amarillasLocalId: ['32', '33'],
    amarillasVisitanteId: ['35', '36'],
    golesLocalId: ['31'],
    golesVisitanteId: [],
    rojasLocalId: ['34'],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '19',
    horario: '15:00',
    equipoLocalId: '2',
    equipoVisitanteId: '11',
    amarillasLocalId: ['81', '55', '82'],
    amarillasVisitanteId: ['23', '22', '85', '62'],
    golesLocalId: ['57'],
    golesVisitanteId: ['23', '84'],
    rojasLocalId: ['83'],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '20',
    horario: '16:10',
    equipoLocalId: '9',
    equipoVisitanteId: '4',
    amarillasLocalId: ['86', '87', '88', '89'],
    amarillasVisitanteId: [],
    golesLocalId: [],
    golesVisitanteId: ['63', '90'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '21',
    horario: '17:20',
    equipoLocalId: '3',
    equipoVisitanteId: '10',
    amarillasLocalId: [],
    amarillasVisitanteId: ['40', '21'],
    golesLocalId: [],
    golesVisitanteId: [],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '22',
    horario: '18:30',
    equipoLocalId: '5',
    equipoVisitanteId: '7',
    amarillasLocalId: ['11', '92', '91'],
    amarillasVisitanteId: [],
    golesLocalId: ['91'],
    golesVisitanteId: ['15', '15', '93', '94'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '23',
    horario: '19:40',
    equipoLocalId: '8',
    equipoVisitanteId: '6',
    amarillasLocalId: ['96', '97'],
    amarillasVisitanteId: ['98'],
    golesLocalId: ['95'],
    golesVisitanteId: ['4'],
    rojasLocalId: [],
    rojasVisitanteId: [],
  },
  {
    jugado: true,
    id: '24',
    horario: '20:50',
    equipoLocalId: '1',
    equipoVisitanteId: '12',
    amarillasLocalId: ['65', '13', '99', '100'],
    amarillasVisitanteId: ['103', '74', '104'],
    golesLocalId: ['2'],
    golesVisitanteId: ['102'],
    rojasLocalId: ['101'],
    rojasVisitanteId: [],
  },
];

export const jugadores: Jugador[] = [
  {
    id: '1',
    equipoId: '1',
    nombre: 'Lucas Rossier',
    fechaNacimiento: '09/04/1998',
    posicion: 'Mediocampista',
  },
  {
    id: '2',
    equipoId: '1',
    nombre: 'Lihuen Segovia Grabois',
    posicion: 'Delantero',
  },
  {
    id: '3',
    equipoId: '1',
    nombre: 'Jair Rossier',
    posicion: 'Defensor',
  },
  {
    id: '4',
    equipoId: '6',
    nombre: 'Milton Amarillo',
  },
  {
    id: '5',
    equipoId: '6',
    nombre: 'Marcos Vincon',
  },
  {
    id: '6',
    equipoId: '6',
    nombre: 'Emiliano Casse',
  },
  {
    id: '7',
    equipoId: '6',
    nombre: 'Joaquin Zermathen',
  },
  {
    id: '8',
    equipoId: '2',
    nombre: 'Santiago Valdez',
  },
  {
    id: '9',
    equipoId: '2',
    nombre: 'Eduardo Maciel',
  },
  {
    id: '10',
    equipoId: '5',
    nombre: 'Mauro Orcellet',
  },
  {
    id: '11',
    equipoId: '5',
    nombre: 'Walter Verón',
  },
  {
    id: '12',
    equipoId: '1',
    nombre: 'Benjamín Charles Mengeon',
  },
  {
    id: '13',
    equipoId: '1',
    nombre: 'Alejandro Barreto',
  },
  {
    id: '14',
    equipoId: '1',
    nombre: 'Gabriel Fleitas',
  },
  {
    id: '15',
    equipoId: '7',
    nombre: 'Brian Castro',
  },
  {
    id: '16',
    equipoId: '7',
    nombre: 'Sebastián Orcellet',
  },
  {
    id: '17',
    equipoId: '7',
    nombre: 'Brian Riquelme',
  },
  {
    id: '18',
    equipoId: '7',
    nombre: 'Daian Godoy',
  },
  {
    id: '19',
    equipoId: '10',
    nombre: 'Facundo Lederhos',
  },
  {
    id: '20',
    equipoId: '10',
    nombre: 'Guido Retamar',
  },
  {
    id: '21',
    equipoId: '10',
    nombre: 'Pablo Gómez',
  },
  {
    id: '22',
    equipoId: '11',
    nombre: 'Fabio Berdala',
  },
  {
    id: '23',
    equipoId: '11',
    nombre: 'Javier Combet',
  },
  {
    id: '24',
    equipoId: '11',
    nombre: 'Juan Gómez',
  },
  {
    id: '25',
    equipoId: '11',
    nombre: 'Emiliano Rodríguez',
  },
  {
    id: '26',
    equipoId: '4',
    nombre: 'Giovanni Fontana',
  },
  {
    id: '27',
    equipoId: '4',
    nombre: 'Eduardo Chareun',
  },
  {
    id: '28',
    equipoId: '4',
    nombre: 'Roger Cruz',
  },
  {
    id: '29',
    equipoId: '3',
    nombre: 'Santiago Rebord',
  },
  {
    id: '30',
    equipoId: '8',
    nombre: 'Fabricio Rougier',
  },
  {
    id: '31',
    equipoId: '12',
    nombre: 'Joel Martínez',
  },
  {
    id: '32',
    equipoId: '12',
    nombre: 'Esteban Valloris',
  },
  {
    id: '33',
    equipoId: '12',
    nombre: 'Guido Benegas',
  },
  {
    id: '34',
    equipoId: '12',
    nombre: 'Ángel Martínez',
  },
  {
    id: '35',
    equipoId: '9',
    nombre: 'Agustín Galves',
  },
  {
    id: '36',
    equipoId: '9',
    nombre: 'Dardo Rivero',
  },
  {
    id: '37',
    equipoId: '4',
    nombre: 'Pehuen Amarillo',
  },
  {
    id: '38',
    equipoId: '4',
    nombre: 'Alejandro Galves',
  },
  {
    id: '39',
    equipoId: '10',
    nombre: 'Franco Fernández',
  },
  {
    id: '40',
    equipoId: '10',
    nombre: 'Alejo Zermathen',
  },
  {
    id: '41',
    equipoId: '10',
    nombre: 'Javier Martínez',
  },
  {
    id: '42',
    equipoId: '6',
    nombre: 'Leandro Acevedo',
  },
  {
    id: '43',
    equipoId: '7',
    nombre: 'Brian Giménez',
  },
  {
    id: '44',
    equipoId: '7',
    nombre: 'Axel Faure',
  },
  {
    id: '45',
    equipoId: '7',
    nombre: 'Marcos Durand',
  },
  {
    id: '46',
    equipoId: '1',
    nombre: 'Brian Charles Mengeon',
  },
  {
    id: '47',
    equipoId: '11',
    nombre: 'Cristian López',
  },
  {
    id: '48',
    equipoId: '11',
    nombre: 'Milton Collajovsky',
  },
  {
    id: '49',
    equipoId: '11',
    nombre: 'Matías Benítez',
  },
  {
    id: '50',
    equipoId: '9',
    nombre: 'Alexis Aranda',
  },
  {
    id: '51',
    equipoId: '5',
    nombre: 'Héctor Velzi',
  },
  {
    id: '52',
    equipoId: '5',
    nombre: 'José Bogao',
  },
  {
    id: '53',
    equipoId: '5',
    nombre: 'Federico Rojas',
  },
  {
    id: '54',
    equipoId: '3',
    nombre: 'Federico Morinico',
  },
  {
    id: '55',
    equipoId: '2',
    nombre: 'Sergio Vera',
  },
  {
    id: '56',
    equipoId: '2',
    nombre: 'Franco González',
  },
  {
    id: '57',
    equipoId: '2',
    nombre: 'Franco Fleitas',
  },
  {
    id: '58',
    equipoId: '8',
    nombre: 'Yamil Moreyra',
  },
  {
    id: '59',
    equipoId: '8',
    nombre: 'Facundo Rougier',
  },
  {
    id: '60',
    equipoId: '7',
    nombre: 'Damián Noir Dodera',
  },
  {
    id: '61',
    equipoId: '11',
    nombre: 'Alvaro Gay',
  },
  {
    id: '62',
    equipoId: '11',
    nombre: 'Ernesto Barrios',
  },
  {
    id: '63',
    equipoId: '4',
    nombre: 'Sebastián Iribarren',
  },
  {
    id: '64',
    equipoId: '4',
    nombre: 'Ariel Figueroa',
  },
  {
    id: '65',
    equipoId: '1',
    nombre: 'Gerardo Blanc',
  },
  {
    id: '66',
    equipoId: '9',
    nombre: 'Lucas Silva',
  },
  {
    id: '67',
    equipoId: '9',
    nombre: 'Eric Castillo',
  },
  {
    id: '68',
    equipoId: '9',
    nombre: 'Catriel Ríos',
  },
  {
    id: '69',
    equipoId: '8',
    nombre: 'Aníbal Cuello',
  },
  {
    id: '70',
    equipoId: '8',
    nombre: 'Alberto Martínez',
  },
  {
    id: '71',
    equipoId: '8',
    nombre: 'Johan Rougier',
  },
  {
    id: '72',
    equipoId: '8',
    nombre: 'German Zuchuat',
  },
  {
    id: '73',
    equipoId: '8',
    nombre: 'Alejandro Joannas',
  },
  {
    id: '74',
    equipoId: '12',
    nombre: 'Marcio Sacks',
  },
  {
    id: '75',
    equipoId: '3',
    nombre: 'Emiliano Aguilera',
  },
  {
    id: '76',
    equipoId: '3',
    nombre: 'Daniel Fleitas',
  },
  {
    id: '77',
    equipoId: '10',
    nombre: 'Ariel Retamar',
  },
  {
    id: '78',
    equipoId: '10',
    nombre: 'Ricardo Fernández',
  },
  {
    id: '79',
    equipoId: '10',
    nombre: 'Facundo Canel',
  },
  {
    id: '80',
    equipoId: '10',
    nombre: 'Danilo Milan',
  },
  {
    id: '81',
    equipoId: '2',
    nombre: 'Sergio Buffet',
  },
  {
    id: '82',
    equipoId: '2',
    nombre: 'Lautaro Giménez',
  },
  {
    id: '83',
    equipoId: '2',
    nombre: 'Nicolás Duarte',
  },
  {
    id: '84',
    equipoId: '11',
    nombre: 'Nicolás Walser',
  },
  {
    id: '85',
    equipoId: '11',
    nombre: 'Ezequiel Amarillo',
  },
  {
    id: '86',
    equipoId: '9',
    nombre: 'Gonzalo Droz',
  },
  {
    id: '87',
    equipoId: '9',
    nombre: 'Ubaldo Palacio',
  },
  {
    id: '88',
    equipoId: '9',
    nombre: 'Atilio Silva',
  },
  {
    id: '89',
    equipoId: '9',
    nombre: 'Ismael Benítez',
  },
  {
    id: '90',
    equipoId: '4',
    nombre: 'Cristian Cobello',
  },
  {
    id: '91',
    equipoId: '5',
    nombre: 'Cristian Meichtry',
  },
  {
    id: '92',
    equipoId: '5',
    nombre: 'Héctor Bogao',
  },
  {
    id: '93',
    equipoId: '7',
    nombre: 'Rafael Benítez',
  },
  {
    id: '94',
    equipoId: '7',
    nombre: 'Daian González',
  },
  {
    id: '95',
    equipoId: '8',
    nombre: 'Lucas Lugrin',
  },
  {
    id: '96',
    equipoId: '8',
    nombre: 'Bruno Dimotta',
  },
  {
    id: '97',
    equipoId: '8',
    nombre: 'Sebastián Forclaz',
  },
  {
    id: '98',
    equipoId: '6',
    nombre: 'Juan Paiva',
  },
  {
    id: '99',
    equipoId: '1',
    nombre: 'Juan Derkaes',
  },
  {
    id: '100',
    equipoId: '1',
    nombre: 'Facundo González',
  },
  {
    id: '101',
    equipoId: '1',
    nombre: 'Silvio Mattiauda',
  },
  {
    id: '102',
    equipoId: '12',
    nombre: 'Ramiro Constante',
  },
  {
    id: '103',
    equipoId: '12',
    nombre: 'Darío Balbuena',
  },
  {
    id: '104',
    equipoId: '12',
    nombre: 'Federico Martínez',
  },
];
